export const BUSES_ROUTES_FALLBACK_BUSES = [
  {
    id: 'fl-4289-x',
    plate: 'FL-4289-X',
    model: 'SCANIA TOURING HD',
    capacity: 40,
    uptime: 98,
    age: '2y',
    status: 'active',
    drivers: ['Ava', 'Ben', 'Chris'],
    maintenanceNote: '',
  },
  {
    id: 'fl-9901-b',
    plate: 'FL-9901-B',
    model: 'VOLVO B11R',
    capacity: 52,
    uptime: 82,
    age: '5y',
    status: 'maintenance',
    drivers: [],
    maintenanceNote: 'Service due in 3 days',
  },
  {
    id: 'fl-2144-k',
    plate: 'FL-2144-K',
    model: 'MERCEDES-BENZ TRAVEGO',
    capacity: 40,
    uptime: 94,
    age: '1y',
    status: 'active',
    drivers: ['Dana', 'Eli'],
    maintenanceNote: '',
  },
]

export const BUSES_ROUTES_FALLBACK_ROUTES = [
  {
    id: 'london-manchester',
    origin: 'London',
    destination: 'Manchester',
    subtitle: 'Intercity Express Loop',
    distance: 320,
    averageTime: '4h 15m',
    stops: 3,
    status: 'active',
    demandLabel: 'High Demand',
    demandTone: 'high',
    activeBuses: 12,
    start: [51.5074, -0.1278],
    end: [53.4808, -2.2426],
  },
  {
    id: 'birmingham-leeds',
    origin: 'Birmingham',
    destination: 'Leeds',
    subtitle: 'Night Shift Regional',
    distance: 180,
    averageTime: '2h 45m',
    stops: 5,
    status: 'suspended',
    demandLabel: 'Temporarily Suspended',
    demandTone: 'suspended',
    activeBuses: 0,
    start: [52.4862, -1.8904],
    end: [53.8008, -1.5491],
  },
  {
    id: 'london-edinburgh',
    origin: 'London',
    destination: 'Edinburgh',
    subtitle: 'Overnight Luxury Sleeper',
    distance: 640,
    averageTime: '8h 30m',
    stops: 2,
    status: 'active',
    demandLabel: 'Premium Route',
    demandTone: 'premium',
    activeBuses: 8,
    start: [51.5074, -0.1278],
    end: [55.9533, -3.1883],
  },
]
