/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/user/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/user/AppHeader.vue')['default']
    BaseAvatar: typeof import('./src/components/elements/BaseAvatar.vue')['default']
    BaseBell: typeof import('./src/components/elements/BaseBell.vue')['default']
    BaseButton: typeof import('./src/components/elements/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/elements/BaseCard.vue')['default']
    BaseDataTable: typeof import('./src/components/elements/BaseDataTable.vue')['default']
    BaseEmptyState: typeof import('./src/components/elements/BaseEmptyState.vue')['default']
    BaseFormSelectPayment: typeof import('./src/components/common/BaseFormSelectPayment.vue')['default']
    BaseInput: typeof import('./src/components/elements/BaseInput.vue')['default']
    BaseMapCar: typeof import('./src/components/common/BaseMapCar.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    BasePagination: typeof import('./src/components/elements/BasePagination.vue')['default']
    BaseSavePaymentForm: typeof import('./src/components/common/BaseSavePaymentForm.vue')['default']
    BaseSearchForm: typeof import('./src/components/common/BaseSearchForm.vue')['default']
    BaseSortFilter: typeof import('./src/components/elements/BaseSortFilter.vue')['default']
    BaseTabs: typeof import('./src/components/elements/BaseTabs.vue')['default']
    BaseTicketCard: typeof import('./src/components/common/BaseTicketCard.vue')['default']
    BaseToggleSwitch: typeof import('./src/components/elements/BaseToggleSwitch.vue')['default']
    BaseTrendChart: typeof import('./src/components/elements/BaseTrendChart.vue')['default']
    BaseTripCard: typeof import('./src/components/common/BaseTripCard.vue')['default']
    DriverVehiclePanel: typeof import('./src/components/common/DriverVehiclePanel.vue')['default']
    FleetBusCard: typeof import('./src/components/common/FleetBusCard.vue')['default']
    Footer: typeof import('./src/components/layout/admin/Footer.vue')['default']
    Header: typeof import('./src/components/layout/admin/Header.vue')['default']
    ModalCreateBus: typeof import('./src/components/common/Modal/ModalCreateBus.vue')['default']
    ModalCreateRoute: typeof import('./src/components/common/Modal/ModalCreateRoute.vue')['default']
    ModalCreateTrip: typeof import('./src/components/common/Modal/ModalCreateTrip.vue')['default']
    ModalDeleteConfirm: typeof import('./src/components/common/Modal/ModalDeleteConfirm.vue')['default']
    ModalTripDetails: typeof import('./src/components/common/Modal/ModalTripDetails.vue')['default']
    ModalUserForm: typeof import('./src/components/common/Modal/ModalUserForm.vue')['default']
    ModalUserStatus: typeof import('./src/components/common/Modal/ModalUserStatus.vue')['default']
    RevenueBusTable: typeof import('./src/components/common/RevenueBusTable.vue')['default']
    RevenueDensityHeatmap: typeof import('./src/components/common/RevenueDensityHeatmap.vue')['default']
    RevenueRouteChart: typeof import('./src/components/common/RevenueRouteChart.vue')['default']
    RevenueSummaryCard: typeof import('./src/components/common/RevenueSummaryCard.vue')['default']
    RouteMiniMap: typeof import('./src/components/common/RouteMiniMap.vue')['default']
    RouteNetworkCard: typeof import('./src/components/common/RouteNetworkCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/admin/Sidebar.vue')['default']
    StaffPerformancePanel: typeof import('./src/components/common/StaffPerformancePanel.vue')['default']
    StatusToggle: typeof import('./src/components/common/StatusToggle.vue')['default']
    ToastContainer: typeof import('./src/components/common/ToastContainer.vue')['default']
    TripHighlightCard: typeof import('./src/components/common/TripHighlightCard.vue')['default']
    TripsCalendarGrid: typeof import('./src/components/common/TripsCalendarGrid.vue')['default']
    TripsListTable: typeof import('./src/components/common/TripsListTable.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  }
}
