export const TRIP_VIEW_FALLBACK_TRIPS = [
  {
    id: 1,
    departureTime: '08:00',
    departurePeriod: 'AM',
    arrivalTime: '09:30',
    arrivalPeriod: 'AM',
    busPlate: '29A-123.45',
    availableSeats: 15,
    totalSeats: 40,
    price: 150000,
  },
  {
    id: 2,
    departureTime: '09:15',
    departurePeriod: 'AM',
    arrivalTime: '10:45',
    arrivalPeriod: 'AM',
    busPlate: '29B-987.65',
    availableSeats: 8,
    totalSeats: 40,
    price: 150000,
  },
  {
    id: 3,
    departureTime: '10:30',
    departurePeriod: 'AM',
    arrivalTime: '12:00',
    arrivalPeriod: 'PM',
    busPlate: '15A-555.55',
    availableSeats: 4,
    totalSeats: 22,
    price: 220000,
  },
  {
    id: 4,
    departureTime: '13:00',
    departurePeriod: 'PM',
    arrivalTime: '14:30',
    arrivalPeriod: 'PM',
    busPlate: '29C-456.78',
    availableSeats: 20,
    totalSeats: 40,
    price: 150000,
  },
  {
    id: 5,
    departureTime: '15:45',
    departurePeriod: 'PM',
    arrivalTime: '17:15',
    arrivalPeriod: 'PM',
    busPlate: '29D-321.00',
    availableSeats: 12,
    totalSeats: 40,
    price: 150000,
  },
]

export const TRIP_VIEW_SORT_OPTIONS = [
  { label: 'Earliest', value: 'earliest' },
  { label: 'Latest', value: 'latest' },
  { label: 'Cheapest', value: 'price-asc' },
]
